theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true  
github:
  is_project_page: false
 
title: Conversational End-to-End TTS for Voice Agents
description: >
  Anonymous Authors\n
  Anonymous Affiliations
